name: Linting

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    eslint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout du repo
              uses: actions/checkout@v4

            - name: Installation de Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "npm"

            - name: Installation des dépendances
              run: npm ci

            - name: Vérification ESLint
              run: npm run lint
